### ISSUE TITLE
API Keys are visible in code

### ISSUE THREAD

**Issue by akraus53** [felhag/lastfm-stats-web#38]
dont think i need to add anything to this

**Comment by felhag** [comment]
Closing this issue for now due inactivity.

**Comment by akraus53** [comment]
Hi, sorry for not responding. Buzy time, full inbox. I could have been more eloquent with my issue description... I guess it's fine for lastfm because you can create keys so easily and there's no billing. Still, maybe some guy with a lot of free time might decide to try and find a way to get a key deactivated? 

Anyway, I'm not into front end programming, but if this was python, I'd make a new file, commit it once, add it to gitignore and then add the key to the file. Again, not sure if this applies here. With network tools you'd probably still find the key, but at least not on GitHub.

**Comment by NoWarries** [comment]
> Hi, sorry for not responding. Buzy time, full inbox. I could have been more eloquent with my issue description... I guess it's fine for lastfm because you can create keys so easily and there's no billing. Still, maybe some guy with a lot of free time might decide to try and find a way to get a key deactivated?
> 
> Anyway, I'm not into front end programming, but if this was python, I'd make a new file, commit it once, add it to gitignore and then add the key to the file. Again, not sure if this applies here. With network tools you'd probably still find the key, but at least not on GitHub.

There is really no way to prevent the exposure of the API key in the network tool due to the nature of the request(s). The code owner could implement a proxyserver [2, 3] of some sort, but this could cost the codeowner more than they're willing to spend, especially for such a detail. Hiding the API key on GitHub is considered best practice [1]; however, if it is not concealed within the web application, the effort becomes essentially pointless.

A possible resolution could be prompting users to supply their own API key, but this could introduce a significant barrier for users, making the service less approachable.

[1] “Keeping your API credentials secure - GitHub Docs”, GitHub Docs, 28 november 2022. https://docs.github.com/en/rest/authentication/keeping-your-api-credentials-secure?apiVersion=2022-11-28#use-authentication-credentials-securely-in-your-code
[2] Wikipedia contributors, “Proxy server”, Wikipedia, 28 december 2023. https://en.wikipedia.org/wiki/Proxy_server
[3] “Using a reverse proxy to protect third party APIs”. https://approov.io/blog/using-a-reverse-proxy-to-protect-third-party-apis/
