### ISSUE TITLE
Highlight Certain Artists/Tracks/Albums in All Scrobbles

### ISSUE THREAD

**Issue by makeamovie** [felhag/lastfm-stats-web#50]
It would be cool if we could choose to highlight certain artists/tracks/albums in the all scrobbles graph with different colors. Either that or change the color of a data point if it's the first time listening to an artist/track/album. Not something that HAS to be added, but it would still be cool nonetheless.

**Comment by felhag** [comment]
Sound indeed like a nice feature :)

**Comment by felhag** [comment]
I had a try to implement this, but I'm afraid it is not that straight forward. I use some boosting modules to keep it performant since the chart can contain hundred thousands of data points (depending on your amount of scrobbles of course). To change the color for a specific artist I had to disable the boosting module which made the performance really bad. That said, the visual result was kinda of disappointing too (although this might could have been improved by increasing the dot size for the highlighted artist). For example; this was the result when highlighting the most scrobbles artist for my own account:

![scrobbles](https://github.com/user-attachments/assets/862f5d2a-a82f-48ca-9bcc-5181a9c28d5e)
