### ISSUE TITLE
Loss of statistics

### ISSUE THREAD

**Issue by Pinker75** [felhag/lastfm-stats-web#60]
Today I discovered that the integration between Spotify and LastFM was disabled for some reason 2 days ago. Accordingly, the listening statistics for these 2 days were not included in Lastfm.stats. My listened streak is more than 300 days, and I would not like to lose this achievement.  Is there any way to upload statistics for these days to Lastfm.stats?

**Comment by felhag** [comment]
Preferably I think you should try to fix this in last.fm itself. Maybe with something like [OpenScrobbler](https://openscrobbler.com/) you could achieve this (haven't used it myself but according to the homepage it provides a possibility to manually add scrobbles to you lastfm profile).

An alternative solution would be to modify your lastfmstats export file (csv/json/db). But this will be quite labor intensive and the export isn't necessarily ment as primary source.

So I would definitely recommend the first solution. After you added it to your profile you need to delete your saved scrobbles since it only starts loading from the last saved scrobble.

**Comment by Pinker75** [comment]
Thank you very much, the method works! I got the stats from Spotify and then through OpenScrobbler uploaded all the data to LastFM manually. I will keep this option in mind in case of force majeure

**Comment by felhag** [comment]
Awesome, great to hear. I'll mark the issue as solved.
